### ISSUE TITLE
Edit Documentation

### ISSUE THREAD

**Issue by ljl7123** [ochorocho/gitlab-mirror-pull#10]
My university technical writing course has an assignment which involves editing documentation on GitHub repositories as practice in real world settings. Edits may involve aspects like style, structure, and concision.

Existing style guidelines would be taken into account. The following is one of the resources I would be using:
https://jacobian.org/writing/technical-style/

Would anyone mind if I propose edits to documentation in this repository? It would really help me out!

**Comment by ochorocho** [comment]
Hey, all contributions all welcome. Just fork this repo, do your changes and create a Merge request.
Thanks :-)

**Comment by ochorocho** [comment]
Changes merged.
